# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint --fix
          - npm run build
    - step:
        name: Beta Deploy
        deployment: beta-deploy
        script:
          - pipe: atlassian/firebase-deploy:0.3.4
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: 'beta-flourigh'
              EXTRA_ARGS: '--only hosting:beta-catalog-mobile'
