version: 2
jobs:
  build:
      docker:
          - image: circleci/node:10.16.0
      working_directory: ~/repo
      steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
          - run:
                name: Install Dependencies
                command: >
                    npm install &&
                    npm run build &&
                    echo '{' >> firebase.json &&
                    echo '  "hosting"&#58; {' >> firebase.json &&
                    echo '    "public"&#58; "dist",' >> firebase.json &&
                    echo '    "site"&#58; "beta-catalog-mobile",' >> firebase.json &&
                    echo '    "ignore"&#58; [' >> firebase.json &&
                    echo '      "firebase.json",' >> firebase.json &&
                    echo '      "**/.*",' >> firebase.json &&
                    echo '      "**/node_modules/**"' >> firebase.json &&
                    echo '    ],' >> firebase.json &&
                    echo '    "rewrites"&#58; [' >> firebase.json &&
                    echo '      {' >> firebase.json &&
                    echo '        "source"&#58; "**",' >> firebase.json &&
                    echo '        "destination"&#58; "/index.html"' >> firebase.json &&
                    echo '      }' >> firebase.json &&
                    echo '    ]' >> firebase.json &&
                    echo '  }' >> firebase.json &&
                    echo '}' >> firebase.json &&
                    echo '{' >> .firebaserc &&
                    echo '  "projects"&#58; {' >> .firebaserc &&
                    echo '    "default"&#58; "beta-flourigh"' >> .firebaserc &&
                    echo '  }' >> .firebaserc &&
                    echo '}' >> .firebaserc
          - save_cache:
                key: v1-npm-deps-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
          - run:
                name: Firebase Deploy
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
